### ISSUE TITLE
ARHighRise-master/HighRiseAR/ViewController.swift:86:65: 'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals

### ISSUE THREAD

**Issue by ugur10** [JeddJedd/ARHighRise#1]
Hi, 

Great work! Couldn't make it up and running even after getting the missing .scn and SCN Extensions class from the original project at Ray Wenderlich. Could you help me out on this?

Thanks!

**Comment by JeddGoble** [comment]
Hi @ugur10, thanks! That's a bummer it's not running. Which file is missing for you?

Just before I start trying to track down the issue, can you let me know which version of Xcode you're running? Also if you could list any additional error(s) that'd be super helpful.

I will create another directory and pull the repo in an attempt to reproduce.

**Comment by ugur10** [comment]
Hey,
I copied the missing resources from the HighRise on RayWenderlich.
I am on Xcode 9 Beta 4. Will try again soon

**Comment by JeddGoble** [comment]
I think I've resolved it. The issue was two-fold:

The Xcode project was referencing the GameScene.scn and SCN extension files in a local directory that weren't part of the repo.

Swift 4 deprecated `UIColor(colorLiteralRed:` and I've changed this to `UIColor(red:` ....

Please pull from master again and give it another shot.

**Comment by ugur10** [comment]
OK I am on it.

It says this

    0x1016c16b0 <+72>:  bl     0x1016dc3e8               ; swift_rt_swift_allocObject
    0x1016c16b4 <+76>:  mov    x8, x0
    0x1016c16b8 <+80>:  stp    x22, x21, [x8, #0x10]
    0x1016c16bc <+84>:  strb   w20, [x8, #0x20]
    0x1016c16c0 <+88>:  str    w19, [x8, #0x24]
    0x1016c16c4 <+92>:  adr    x3, #0x95d04              ; partial apply forwarder for closure #2 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._fatalErrorMessage(Swift.StaticString, Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never
    0x1016c16c8 <+96>:  nop    
    0x1016c16cc <+100>: mov    x0, x25
    0x1016c16d0 <+104>: mov    x1, x24
    0x1016c16d4 <+108>: mov    x2, x23
    0x1016c16d8 <+112>: mov    x4, x8
    0x1016c16dc <+116>: bl     0x101537544               ; function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer<A>((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A
->  0x1016c16e0 <+120>: brk    #0x1


Crashes on SCN scene init on viewDidLoad

2017-07-30 16:13:44.323875+0300 HighRiseAR[4817:1763365] fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb)

**Comment by JeddGoble** [comment]
Oof. I should never use the bang operator! ;) As said, this was sorta thrown together.

Ok let me see. Will get back to you shortly.

**Comment by ugur10** [comment]
Hey man, no worries. I am shocked to see you so responsive...you are awesome but please don't be nervous about it. It is super cool to share a project like this, quite an inspiration. Let me know when you fix it :)

**Comment by JeddGoble** [comment]
No prob, whole point of having it on GitHub is so that people can check it out No sense in letting it sit there without it working! So I appreciate you bringing it to my attention.

I've repro'd the issue you have and will let you know when I figure out the cause.

**Comment by JeddGoble** [comment]
This is really weird. I tried a few different things ... even tried accessing the ARKit's built-in `art.scnassets/ship.scn` from that line of code, and it's still nil. Need to head out soon but I'd recommend Googling some SceneKit stuff on StackOverflow and see if you can find a remedy for why it's not locating that file.

If you manage to fix it feel free to submit your changes. :D

**Comment by JeddGoble** [comment]
Figured it out. Turns out the problem is that the SCN was there, but the SCN "background" was nil. So it nil'd the whole thing! Please pull master and let me know if it works for you now.
